from django.db import models
from system.models.common import BaseContent

class SalesReturns(BaseContent):
    invoice = models.ForeignKey('SalesInvoices', on_delete = models.CASCADE, null = True, blank = True)
    customer = models.ForeignKey('Customers', on_delete = models.CASCADE, null = True, blank = True)
    contact_address = models.ForeignKey('Addresses', on_delete = models.SET_NULL, null = True, blank = True, related_name="%(class)s_contact_address")
    contact_first = models.CharField(max_length = 255, null = True, blank = True)
    contact_last = models.CharField(max_length = 255, null = True, blank = True)
    contact_telephone = models.CharField(max_length = 255, null = True, blank = True)
    contact_email = models.CharField(max_length = 255, null = True, blank = True)
    billing_address = models.ForeignKey('Addresses', on_delete = models.SET_NULL, null = True, blank = True, related_name="%(class)s_billing_address")
    billing_first = models.CharField(max_length = 255, null = True, blank = True)
    billing_last = models.CharField(max_length = 255, null = True, blank = True)
    billing_company = models.CharField(max_length = 255, null = True, blank = True)
    billing_address_1 = models.CharField(max_length = 255, null = True, blank = True)
    billling_address_2 = models.CharField(max_length = 255, null = True, blank = True)
    billing_address_3 = models.CharField(max_length = 255, null = True, blank = True)
    billing_city = models.CharField(max_length = 255, null = True, blank = True)
    billing_state = models.ForeignKey('system.State', on_delete=models.SET_NULL, null=True, blank=True, related_name="%(class)s_billing_state")
    billing_postal_code = models.CharField(max_length = 255, null = True, blank = True)
    billing_country = models.ForeignKey('system.Country', on_delete=models.SET_NULL, null=True, blank=True, related_name="%(class)s_blling_country")
    billing_telephone = models.CharField(max_length = 255, null = True, blank = True)
    billing_email = models.CharField(max_length = 255, null = True, blank = True)
    billing_note = models.TextField(null = True, blank = True)
    return_address = models.ForeignKey('Addresses', on_delete = models.SET_NULL, null = True, blank = True, related_name="%(class)s_return_address")
    return_first = models.CharField(max_length = 255, null = True, blank = True)
    return_last = models.CharField(max_length = 255, null = True, blank = True)
    return_company = models.CharField(max_length = 255, null = True, blank = True)
    return_address_1 = models.CharField(max_length = 255, null = True, blank = True)
    return_address_2 = models.CharField(max_length = 255, null = True, blank = True)
    return_address_3 = models.CharField(max_length = 255, null = True, blank = True)
    return_city = models.CharField(max_length = 255, null = True, blank = True)
    return_state = models.ForeignKey('system.State', on_delete=models.SET_NULL, null=True, blank=True, related_name="%(class)s_return_state")
    return_postal_code = models.CharField(max_length = 255, null = True, blank = True)
    return_country = models.ForeignKey('system.Country', on_delete=models.SET_NULL, null=True, blank=True, related_name="%(class)s_return_country")
    return_date = models.DateTimeField(null = True, blank = True)
    reference = models.CharField(max_length = 255, null = True, blank = True)
    refund_terms = models.CharField(max_length = 255, null = True, blank = True)
    shipping_terms = models.CharField(max_length = 255, null = True, blank = True)
    currency = models.ForeignKey('system.Currency', on_delete = models.SET_NULL, null= True, blank = True)
    merchandise = models.DecimalField(max_digits=30,decimal_places=2,null=True, blank=True)
    other = models.DecimalField(max_digits=30,decimal_places=2,null=True, blank=True)
    tax = models.DecimalField(max_digits=30,decimal_places=2,null=True, blank=True)
    shipping = models.DecimalField(max_digits=30,decimal_places=2,null=True, blank=True)
    total = models.DecimalField(max_digits=30,decimal_places=2,null=True, blank=True)
    return_stage = models.ForeignKey('system.Stage', on_delete=models.SET_NULL, null=True, blank=True)
    stage_started = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=255, null=True, blank=True)

class SalesReturnLines(BaseContent):
    stock_id = models.CharField(max_length = 255, null = True, blank = True)#FKEY
    stock_number = models.CharField(max_length=255, null=True, blank=True)
    product_name = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null = True, blank = True)
    list_price = models.DecimalField(max_digits=30,decimal_places=2,null=True, blank=True)
    multiplier = models.DecimalField(max_digits=30,decimal_places=2,null=True, blank=True)
    uom = models.CharField(max_length = 255, null = True, blank = True)#FKEY
    route = models.CharField(max_length=255, null=True, blank=True)#Fkey
    quantity = models.DecimalField(max_digits=30,decimal_places=2,null=True, blank=True)#FKEY
    via_choice = models.DecimalField(max_digits=30,decimal_places=2,null=True, blank=True)
    date = models.DateTimeField(null = True, blank = True)
    sequence = models.IntegerField(null=True, blank=True)
    comment = models.TextField(null = True, blank = True)
    stage = models.ForeignKey('system.Stage', on_delete=models.SET_NULL, null=True, blank=True)
    status = models.CharField(max_length=255, null=True, blank=True)
