from django.db import models
from system.models.common import BaseStatus

class SalesReturns(BaseStatus):
    id = models.CharField(max_length=255, primary_key=True, editable=False)
    invoice = models.ForeignKey('SalesInvoices', on_delete = models.CASCADE, null = True, blank = True)
    customer = models.ForeignKey('Customers', on_delete = models.CASCADE, null = True, blank = True)
    contact_address = models.ForeignKey('Addresses', on_delete = models.SET_NULL, null = True, blank = True, related_name="%(class)s_contact_address")
    contact_first = models.CharField(max_length = 255, null = True, blank = True)
    contact_last = models.CharField(max_length = 255, null = True, blank = True)
    contact_telephone = models.CharField(max_length = 255, null = True, blank = True)
    contact_email = models.CharField(max_length = 255, null = True, blank = True)
    credit_address = models.ForeignKey('Addresses', on_delete = models.SET_NULL, null = True, blank = True, related_name="%(class)s_billing_address")
    credit_first = models.CharField(max_length = 255, null = True, blank = True)
    credit_last = models.CharField(max_length = 255, null = True, blank = True)
    credit_company = models.CharField(max_length = 255, null = True, blank = True)
    credit_address_1 = models.CharField(max_length = 255, null = True, blank = True)
    credit_address_2 = models.CharField(max_length = 255, null = True, blank = True)
    credit_address_3 = models.CharField(max_length = 255, null = True, blank = True)
    credit_city = models.CharField(max_length = 255, null = True, blank = True)
    credit_state = models.ForeignKey('system.State', on_delete=models.SET_NULL, null=True, blank=True, related_name="%(class)s_billing_state")
    credit_postal_code = models.CharField(max_length = 255, null = True, blank = True)
    credit_country = models.ForeignKey('system.Country', on_delete=models.SET_NULL, null=True, blank=True, related_name="%(class)s_blling_country")
    credit_telephone = models.CharField(max_length = 255, null = True, blank = True)
    credit_email = models.CharField(max_length = 255, null = True, blank = True)
    credit_note = models.TextField(null = True, blank = True)
    return_address = models.ForeignKey('Addresses', on_delete = models.SET_NULL, null = True, blank = True, related_name="%(class)s_return_address")
    return_first = models.CharField(max_length = 255, null = True, blank = True)
    return_last = models.CharField(max_length = 255, null = True, blank = True)
    return_company = models.CharField(max_length = 255, null = True, blank = True)
    return_address_1 = models.CharField(max_length = 255, null = True, blank = True)
    return_address_2 = models.CharField(max_length = 255, null = True, blank = True)
    return_address_3 = models.CharField(max_length = 255, null = True, blank = True)
    return_city = models.CharField(max_length = 255, null = True, blank = True)
    return_state = models.ForeignKey('system.State', on_delete=models.SET_NULL, null=True, blank=True, related_name="%(class)s_return_state")
    return_postal_code = models.CharField(max_length = 255, null = True, blank = True)
    return_country = models.ForeignKey('system.Country', on_delete=models.SET_NULL, null=True, blank=True, related_name="%(class)s_return_country")
    return_date = models.DateTimeField(null = True, blank = True)
    reference = models.CharField(max_length = 255, null = True, blank = True)
    refund_terms = models.CharField(max_length = 255, null = True, blank = True)
    shipping_terms = models.CharField(max_length = 255, null = True, blank = True)
    currency = models.ForeignKey('system.Currency', on_delete = models.SET_NULL, null= True, blank = True)
    merchandise = models.DecimalField(max_digits=30,decimal_places=2,null=True, blank=True)
    other = models.DecimalField(max_digits=30,decimal_places=2,null=True, blank=True)
    tax = models.DecimalField(max_digits=30,decimal_places=2,null=True, blank=True)
    shipping = models.DecimalField(max_digits=30,decimal_places=2,null=True, blank=True)
    total = models.DecimalField(max_digits=30,decimal_places=2,null=True, blank=True)

class SalesReturnLines(BaseStatus):
    id = models.CharField(max_length=255, primary_key=True, editable=False)
    stock = models.ForeignKey('warehouse.Product', on_delete = models.SET_NULL, null= True, blank = True)
    stock_number = models.CharField(max_length=255, null=True, blank=True) 
    product_name = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null = True, blank = True)
    list_price = models.DecimalField(max_digits=30,decimal_places=2,null=True, blank=True)
    multiplier = models.DecimalField(max_digits=30,decimal_places=2,null=True, blank=True)
    uom = models.ForeignKey('warehouse.UOM', on_delete = models.SET_NULL, null= True, blank = True)
    route = models.ForeignKey('warehouse.Routes', on_delete = models.SET_NULL, null= True, blank = True)
    quantity = models.DecimalField(max_digits=30,decimal_places=2,null=True, blank=True)#FKEY
    via = models.ForeignKey('system.Choice', on_delete=models.SET_NULL, null=True, blank=True, related_name="return_method")
    date_due = models.DateTimeField(null = True, blank = True)
    sequence = models.IntegerField(null=True, blank=True)
    comment = models.TextField(null = True, blank = True)
