# Generated by Django 4.0 on 2023-03-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country',
        ),
        migrations.AddField(
            model_name='country',
            name='country_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.FileField(blank=True, null=True, upload_to='flag/'),
        ),
        migrations.AddField(
            model_name='country',
            name='system_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='native_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
