# Generated by Django 4.0 on 2023-02-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='name',
            new_name='system_name',
        ),
        migrations.AlterField(
            model_name='country',
            name='telephone_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
