# Generated by Django 4.0 on 2023-02-09 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='primary_table',
            new_name='data_source',
        ),
    ]
