# Generated by Django 4.0 on 2023-01-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='edittiable',
        ),
        migrations.AddField(
            model_name='choice',
            name='editable',
            field=models.CharField(blank=True, choices=[('Custom', 'Editable'), ('System', 'Non-Editable')], max_length=50, null=True),
        ),
    ]
