# Generated by Django 4.0 on 2023-02-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_rename_name_data_system_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
