# Generated by Django 4.0 on 2023-01-05 05:56

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_translationmenu_translation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='abbreviation',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name',
        ),
        migrations.AddField(
            model_name='country',
            name='country',
            field=django_countries.fields.CountryField(default=1, max_length=2, unique=True),
            preserve_default=False,
        ),
    ]
