# Generated by Django 4.0 on 2023-01-25 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_remove_choice_edittiable_choice_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.entity'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.choice'),
        ),
    ]
