# Generated by Django 4.0 on 2023-02-24 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_data_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='visibility',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='entity',
        ),
    ]
