# Generated by Django 4.0 on 2023-01-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_menu_entity_menu_menu_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu_type',
        ),
    ]
