# Generated by Django 4.0 on 2023-03-16 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_country_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='button',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.stage'),
        ),
        migrations.AlterField(
            model_name='formlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
