# Generated by Django 4.0 on 2023-01-31 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_list_list_type_alter_list_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listicon',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.icons'),
        ),
    ]
