# Generated by Django 4.0 on 2023-03-16 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('warehouse', '0002_rename_category_id_accounts_category_and_more'),
        ('system', '0005_button_highlight_button_stage_alter_formlist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='form',
        ),
        migrations.AddField(
            model_name='entityaccounts',
            name='accounts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.accounts'),
        ),
        migrations.CreateModel(
            name='FormStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='auth.user')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.form')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.stage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ButtonStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.button')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='auth.user')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.stage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('system_name', models.CharField(max_length=255, unique=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('status_id', models.CharField(blank=True, choices=[('1', 'Closed'), ('2', 'Normal'), ('3', 'Warning'), ('4', 'Urgent')], max_length=1, null=True)),
                ('button', models.ManyToManyField(blank=True, to='system.Button')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='auth.user')),
                ('data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.data')),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.datatable')),
                ('form', models.ManyToManyField(blank=True, to='system.Form')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.choice')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.stage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
