# Generated by Django 4.0 on 2023-01-25 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_menu_entity_menu_menu_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_name',
            new_name='choice',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='deafult',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='editable',
        ),
        migrations.AddField(
            model_name='choice',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='choice',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.form'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='selector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
