# Generated by Django 4.0 on 2023-01-25 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_rename_choice_name_choice_choice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice',
            new_name='choice_name',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='default',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='form',
        ),
        migrations.AddField(
            model_name='choice',
            name='deafult',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('None', '')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='editable',
            field=models.CharField(blank=True, choices=[('Custom', 'Editable'), ('System', 'Non-Editable')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='selector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.choice'),
        ),
    ]
