# Generated by Django 4.0 on 2023-03-20 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_listfilters_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='selector',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='child_field',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='field',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='parent_field',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='type',
        ),
        migrations.AddField(
            model_name='data',
            name='field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='field_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='system_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='data_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_type', to='system.choice'),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='visibility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visibility', to='system.choice'),
        ),
    ]
