# Generated by Django 4.0 on 2023-02-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_alter_list_system_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='data_filter',
        ),
        migrations.RemoveField(
            model_name='list',
            name='data_sort',
        ),
    ]
