# Generated by Django 4.0 on 2023-03-21 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('system', '0008_remove_data_selector_remove_formdata_child_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listfilters',
            name='operator',
        ),
        migrations.AddField(
            model_name='formstage',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buttonstage',
            name='button',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.button'),
        ),
        migrations.AlterField(
            model_name='buttonstage',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.stage'),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.choice'),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='data_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formstage',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.form'),
        ),
        migrations.AlterField(
            model_name='formstage',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.stage'),
        ),
        migrations.CreateModel(
            name='DataSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='auth.user')),
                ('data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.data')),
                ('selector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.selectors')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
