# Generated by Django 4.0 on 2023-03-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_remove_listfilters_operator_formstage_sequence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formlist',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
