# Generated by Django 4.0 on 2023-02-02 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_listfilters_list_alter_listfilters_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='visibility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.choice'),
        ),
    ]
