# Generated by Django 4.0 on 2023-03-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_alter_formlist_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formdata',
            old_name='link',
            new_name='child_field',
        ),
        migrations.AddField(
            model_name='formdata',
            name='line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
