# Generated by Django 4.0 on 2023-02-03 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_form_description_form_form_type_formicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formlist',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.list'),
        ),
    ]
