# Generated by Django 4.0 on 2023-03-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_rename_link_formdata_child_field_formdata_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
