# Generated by Django 4.0 on 2023-02-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_alter_currency_code_alter_currency_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='category',
        ),
        migrations.AddField(
            model_name='configuration',
            name='editable',
            field=models.BooleanField(default=False),
        ),
    ]
