# Generated by Django 4.0 on 2023-02-08 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0023_remove_country_currency_symbol_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.currency'),
        ),
        migrations.AlterField(
            model_name='country',
            name='native_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='telephone_code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
