# Generated by Django 4.0 on 2023-02-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0024_alter_country_currency_alter_country_native_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
