# Generated by Django 4.0 on 2023-02-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0025_state_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='telephone_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
