# Generated by Django 4.0 on 2023-02-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0026_alter_country_telephone_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='telephone_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
