# Generated by Django 4.0 on 2023-02-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0027_alter_country_telephone_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
