# Generated by Django 4.0 on 2023-02-10 06:19

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0028_alter_state_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country',
            field=django_countries.fields.CountryField(max_length=255, unique=True),
        ),
    ]
