# Generated by Django 4.0 on 2023-02-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0029_alter_country_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='editable',
            field=models.BooleanField(),
        ),
    ]
