# Generated by Django 4.0 on 2023-02-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0032_remove_language_date_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
