# Generated by Django 4.0 on 2023-02-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0033_alter_language_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='direction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
