# Generated by Django 4.0 on 2023-02-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0034_alter_language_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='native_Translation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
