# Generated by Django 4.0 on 2023-02-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0035_alter_language_native_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='icons',
            name='usage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
