# Generated by Django 4.0 on 2023-02-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0036_icons_usage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='default_view',
        ),
        migrations.RemoveField(
            model_name='list',
            name='visibility',
        ),
        migrations.AddField(
            model_name='list',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
