# Generated by Django 4.0 on 2023-02-10 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0037_remove_list_default_view_remove_list_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='visibility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visibility', to='system.choice'),
        ),
    ]
