# Generated by Django 4.0 on 2023-02-11 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0039_remove_data_table_data_comment_data_data_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='sequence',
        ),
    ]
