# Generated by Django 4.0 on 2023-02-13 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0040_remove_data_sequence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_type',
            new_name='category_choice',
        ),
    ]
