# Generated by Django 4.0 on 2023-02-13 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0042_remove_menu_entity_menu_description_menu_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='visibility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_visibility', to='system.choice'),
        ),
        migrations.AlterField(
            model_name='list',
            name='visibility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_visibility', to='system.choice'),
        ),
    ]
