# Generated by Django 4.0 on 2023-02-13 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0043_menu_visibility_alter_list_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_category',
        ),
    ]
