# Generated by Django 4.0 on 2023-02-13 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0050_alter_menu_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
    ]
