# Generated by Django 4.0 on 2023-02-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0051_remove_menu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
