# Generated by Django 4.0 on 2023-02-13 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0053_alter_menu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_category', to='system.menu'),
        ),
    ]
