# Generated by Django 4.0 on 2023-02-13 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0054_alter_list_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='position',
            new_name='sequence',
        ),
        migrations.RemoveField(
            model_name='column',
            name='field',
        ),
        migrations.RemoveField(
            model_name='column',
            name='table',
        ),
        migrations.AddField(
            model_name='column',
            name='data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.data'),
        ),
        migrations.AddField(
            model_name='column',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.dataset'),
        ),
        migrations.AddField(
            model_name='column',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
