# Generated by Django 4.0 on 2023-02-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0056_rename_list_column_clist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='category',
        ),
        migrations.RemoveField(
            model_name='list',
            name='label',
        ),
    ]
