# Generated by Django 4.0 on 2023-02-13 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0058_alter_column_clist_alter_column_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='clist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.list'),
        ),
        migrations.AlterField(
            model_name='column',
            name='data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.data'),
        ),
        migrations.AlterField(
            model_name='column',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.dataset'),
        ),
        migrations.AlterField(
            model_name='column',
            name='visibility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.choice'),
        ),
    ]
