# Generated by Django 4.0 on 2023-02-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0060_alter_column_dataset_alter_data_dataset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='editable',
            field=models.BooleanField(default=False),
        ),
    ]
