# Generated by Django 4.0 on 2023-02-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0062_remove_language_dir_choice_alter_language_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='default_view',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
