# Generated by Django 4.0 on 2023-02-15 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0063_list_default_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='visibility',
        ),
    ]
