# Generated by Django 4.0 on 2023-02-15 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0064_remove_menu_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='description',
        ),
    ]
