# Generated by Django 4.0 on 2023-02-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0065_remove_column_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='sequence',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
