# Generated by Django 4.0 on 2023-02-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0068_alter_column_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
