# Generated by Django 4.0 on 2023-02-21 12:58

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0069_alter_column_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, unique=True),
        ),
    ]
