# Generated by Django 4.0 on 2023-02-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0072_alter_translationselector_selector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationtable',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='translationtable',
            name='table',
        ),
        migrations.RemoveField(
            model_name='translationtable',
            name='translation',
        ),
        migrations.DeleteModel(
            name='TranslationEntity',
        ),
        migrations.DeleteModel(
            name='TranslationTable',
        ),
    ]
