# Generated by Django 4.0 on 2023-02-22 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('system', '0073_remove_translationtable_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationIcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='auth.user')),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.icons')),
                ('translation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.translation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
