# Generated by Django 4.0 on 2023-02-23 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0075_alter_translationchoice_translation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationcolumn',
            name='translation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.translation'),
        ),
        migrations.AlterField(
            model_name='translationform',
            name='translation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.translation'),
        ),
        migrations.AlterField(
            model_name='translationstage',
            name='translation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.translation'),
        ),
    ]
