# Generated by Django 4.0 on 2023-02-27 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('system', '0076_alter_translationcolumn_translation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='sequence',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='name',
            new_name='system_name',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='native_Translation',
            new_name='fraction_separator',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='name',
            new_name='menu_category',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='category_choice',
            new_name='menu_type',
        ),
        migrations.RemoveField(
            model_name='column',
            name='clist',
        ),
        migrations.RemoveField(
            model_name='column',
            name='data',
        ),
        migrations.RemoveField(
            model_name='column',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='data',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='data',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='data',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='data',
            name='field',
        ),
        migrations.RemoveField(
            model_name='data',
            name='field_type',
        ),
        migrations.RemoveField(
            model_name='form',
            name='form_type',
        ),
        migrations.RemoveField(
            model_name='icons',
            name='usage',
        ),
        migrations.RemoveField(
            model_name='language',
            name='code',
        ),
        migrations.RemoveField(
            model_name='language',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='list',
            name='primary_table',
        ),
        migrations.RemoveField(
            model_name='list',
            name='visibility',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='description',
        ),
        migrations.AddField(
            model_name='column',
            name='col_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.list'),
        ),
        migrations.AddField(
            model_name='column',
            name='field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='column',
            name='table',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='date_format',
            field=models.CharField(blank=True, choices=[('1', 'MM/DD/YY'), ('2', 'DD/MM/YY'), ('3', 'YY/MM/DD'), ('4', 'MM-DD-YYYY'), ('5', 'DD-MM-YYYY'), ('6', 'YYYY-MM-DD')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='decimal_places',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='symbol_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='thousands_separator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='time_format',
            field=models.CharField(blank=True, choices=[('1', 'HH:MM:SS'), ('2', 'HH:MM:SS XM'), ('3', 'HH:MM'), ('4', 'HH:MM XM')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='button',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='column',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='column',
            name='visibility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.choice'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='currency',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='form',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='formlist',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='help',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='icons',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='list',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listfilters',
            name='data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.data'),
        ),
        migrations.AlterField(
            model_name='listfilters',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listsorts',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='selectors',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stage',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='territories',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tile',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='translation',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='translationchoice',
            name='translation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.translation'),
        ),
        migrations.AlterField(
            model_name='translationcolumn',
            name='column',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.column'),
        ),
        migrations.AlterField(
            model_name='translationcolumn',
            name='translation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.translation'),
        ),
        migrations.AlterField(
            model_name='translationformsection',
            name='translation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.translation'),
        ),
        migrations.AlterField(
            model_name='translationmenu',
            name='translation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.translation'),
        ),
        migrations.AlterField(
            model_name='translationstage',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.stage'),
        ),
        migrations.AlterField(
            model_name='translationstage',
            name='translation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.translation'),
        ),
        migrations.CreateModel(
            name='RecordIdentifiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('record', models.CharField(blank=True, max_length=255)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
                ('starting', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('next', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='auth.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('system_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='auth.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='data',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.datatable'),
        ),
        migrations.AddField(
            model_name='list',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.datatable'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.datatable'),
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
