# Generated by Django 4.0 on 2023-01-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='loc_type',
            field=models.CharField(blank=True, choices=[('company', 'Companies'), ('customer', 'Customers'), ('vendor', 'Vendors')], max_length=255, null=True),
        ),
    ]
