# Generated by Django 4.0 on 2023-02-02 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status_choices',
        ),
    ]
