# Generated by Django 4.0 on 2023-03-16 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='type_id',
            new_name='type',
        ),
    ]
