# Generated by Django 4.0 on 2023-01-06 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_locations_loc_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_lines',
        ),
    ]
