# Generated by Django 4.0 on 2023-02-02 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_form_description_form_form_type_formicon'),
        ('warehouse', '0002_remove_product_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status_choices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.choice'),
        ),
    ]
