# Generated by Django 4.0 on 2023-02-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_product_status_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containertypes',
            name='surcharge',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=30, null=True),
        ),
    ]
