# Generated by Django 4.0 on 2023-02-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_containertypes_surcharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containertypes',
            name='surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
    ]
