# Generated by Django 4.0 on 2023-01-25 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        ('purchasing', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sales', '0002_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderlines',
            name='delivery_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.deliveries'),
        ),
        migrations.AddField(
            model_name='purchaseorderlines',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderlines',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.routes'),
        ),
        migrations.AddField(
            model_name='purchaseorderlines',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.stage'),
        ),
        migrations.AddField(
            model_name='purchaseorderlines',
            name='vendor_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.vendorproducts'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='authorized_by_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.useraddress'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='contact_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_contact_address', to='sales.addresses'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='auth.user'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_purchase_address', to='sales.addresses'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_shipping_address', to='sales.addresses'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='stage_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.stage'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.vendors'),
        ),
        migrations.AddField(
            model_name='manufacturing_orders',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='auth.user'),
        ),
        migrations.AddField(
            model_name='manufacturing_orders',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.stage'),
        ),
        migrations.AddField(
            model_name='manufacturing_order_lines',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.bom'),
        ),
        migrations.AddField(
            model_name='manufacturing_order_lines',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='auth.user'),
        ),
        migrations.AddField(
            model_name='manufacturing_order_lines',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.product'),
        ),
        migrations.AddField(
            model_name='disbursment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='auth.user'),
        ),
        migrations.AddField(
            model_name='disbursment',
            name='currency_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.currency'),
        ),
        migrations.AddField(
            model_name='disbursment',
            name='sales_credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salescredits'),
        ),
        migrations.AddField(
            model_name='disbursment',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.stage'),
        ),
    ]
