# Generated by Django 4.0 on 2023-03-15 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('system', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_entity', to='system.choice'),
        ),
        migrations.AddField(
            model_name='vendors',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.vendors'),
        ),
        migrations.AddField(
            model_name='vendors',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_payment_method', to='system.choice'),
        ),
        migrations.AddField(
            model_name='vendors',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_payment_terms', to='system.choice'),
        ),
        migrations.AddField(
            model_name='vendors',
            name='purchasing_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.currency'),
        ),
        migrations.AddField(
            model_name='vendors',
            name='ship_via',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_shipping_method', to='system.choice'),
        ),
        migrations.AddField(
            model_name='vendors',
            name='shipping_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_shipping_terms', to='system.choice'),
        ),
        migrations.AddField(
            model_name='vendors',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.stage'),
        ),
        migrations.AddField(
            model_name='vendorproducts',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='auth.user'),
        ),
        migrations.AddField(
            model_name='vendorproducts',
            name='hts_code_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customsclassifications'),
        ),
        migrations.AddField(
            model_name='vendorproducts',
            name='nmfc_code_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.nmfc'),
        ),
        migrations.AddField(
            model_name='vendorproducts',
            name='stage_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.stage'),
        ),
    ]
