# Generated by Django 4.0 on 2023-01-05 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesquotations',
            old_name='order_id',
            new_name='quotation_id',
        ),
    ]
