# Generated by Django 4.0 on 2023-01-05 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_rename_order_id_salesquotations_quotation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesquotations',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.customers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesquotations',
            name='quotation_id',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
