# Generated by Django 4.0 on 2023-01-06 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_salesquotations_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorders',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.customers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesorders',
            name='order_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
