# Generated by Django 4.0 on 2023-01-06 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_delete_product_lines'),
        ('sales', '0006_alter_salesorders_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorderlines',
            old_name='list_price',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='salesorderlines',
            old_name='multiplier',
            new_name='net',
        ),
        migrations.RenameField(
            model_name='salesorderlines',
            old_name='ready',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='salesorderlines',
            old_name='bundle_line_id',
            new_name='via_choice',
        ),
        migrations.RemoveField(
            model_name='salesorderlines',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='salesorderlines',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='salesorderlines',
            name='orderline_stage',
        ),
        migrations.RemoveField(
            model_name='salesorderlines',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='salesorderlines',
            name='released',
        ),
        migrations.RemoveField(
            model_name='salesorderlines',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='salesorderlines',
            name='shipment_id',
        ),
        migrations.RemoveField(
            model_name='salesorderlines',
            name='status',
        ),
        migrations.RemoveField(
            model_name='salesorderlines',
            name='via_choice_id',
        ),
        migrations.AlterField(
            model_name='salesorderlines',
            name='canceled',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderlines',
            name='invoiced',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderlines',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesorders'),
        ),
        migrations.AlterField(
            model_name='salesorderlines',
            name='ordered',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderlines',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.product'),
        ),
        migrations.AlterField(
            model_name='salesorderlines',
            name='reserved',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderlines',
            name='route_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.routes'),
        ),
        migrations.AlterField(
            model_name='salesorderlines',
            name='shipped',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderlines',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.uom'),
        ),
    ]
